name: Build - All Platforms

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - 'husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'
      - '.github/ISSUE_TEMPLATE/**'
      - '.cursor/**'
      - '*_example'

jobs:
  build-windows-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_windows.yml
  build-apple-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_macos.yml
